### ISSUE TITLE
suggestion on config scanner

### ISSUE THREAD

**Issue by thilllon** [woowabros/nestjs-library-config#121]
Here's my roadmap to update the config scanner

- support CLI.
  currently, scanner is executed by `ts-node`. It would be utilizable if it supports CLI. Here's myy expectation of usage:

```sh
npx nestjs-library-scan ./project_1/src,./project_2/src --option1 foo --option2 bar 
```

- support `.env.*` file as output file format. 
  currently, it only supports json and `markdown` as output file. But in
   some use cases, generating `.env.example` with comments would be more helpful, such as making boilerplate project. And I think, `.env.example` is quite intuitive what it does and well known filename in opensource community. Of course, it also supports customization of filename, as well, like `.env.sample` or `example.env`
```env
# variableName: port
# groups: AppConfigService
# defaultValue: 3000
# conditions: IsNumber
PORT=

# variableName: healthCheckPath
# groups: AppConfigService
# defaultValue:
# conditions: IsString, IsOptional
HEALTH_CHECK_PATH=

# ...
```

- support formatting using prettier.
  Currently, scanner updates `README.md` with its own formatting rule, but in some cases, `README.md` file is already formatted via `prettier` and this can cause formatting inconsistency. So, I suggest that user can provide a boolean formatting option which can be formatted with existing formatting options(especially `prettier config`)

```sh
# to format with existing `prettier` configuration file
npx nestjs-library-scan ./project_1/src --format
```

What do you think? @jiho-kr @Pigrabbit @lavelee

**Comment by jiho-kr** [comment]
My opinion is that it's their choice to use `prettier`.

A prettier would be helpful for config-scanner to `write a README`,
but I don't think a prettier can be forced for this.


If config-scanner doesn't have prettier built-in, they should have no problem applying it.
