### ISSUE TITLE
[Question] how to disable Logger In onModuleInit

### ISSUE THREAD

**Issue by youngsu5582** [woowabros/nestjs-library-config#276]
Thank you about really good Proejct!!
I also agree @nestjs/config is just use all ENV element ( not useful part env element )

But , I use this library and find one question

<img width="685" alt="image" src="https://github.com/woowabros/nestjs-library-config/assets/98307410/60dea082-622f-41ac-8f6d-9cb0e318eedd">

[Code Link](https://github.com/woowabros/nestjs-library-config/blob/ddadb22cb26a9baf7377fb4dacaa6f147a5205a4/src/lib/abstract/abstract-config.service.ts#L31)

This code make always logging with key and secret value

So , I want to know why design with always logging 

I am currently a student studying, and I may not be well aware of complex situations, 
so I am asking this question. I would be grateful if you could kindly teach me with a good heart!

##### Suggestion

Make nest-library-config.ts , add Logging Option!
    
``` typescript
type INestConfig= {
    log : boolean;
}

export const NEST_CONFIG : INestConfig ={
    log:true
}
export default NEST_CONFIG;
```

then , checking this option.
```typescript
try {
    // Import CONFIG FILE in project folder
    NEST_CONFIG = require('./nest-library-config').NEST_CONFIG;
} catch (error) {
    // If Not Exist File , Create Default Option.
    NEST_CONFIG = { log: true };
    // OR
    NEST_CONFIG = require('./nest-library-config').DEFAULT_CONFIG;
}
```

Thank you once again !!
If I get the chance, I would like to think more deeply about it and even contribute to this projects

**Comment by jiho-kr** [comment]
Hi, @youngsu5582 

I didn't want to create `separate setting` or `magic words` for logging.

I expect to control logging through Log level.

**Comment by youngsu5582** [comment]
I understand `I didn't want to create separate setting or magic words for logging.` this syntax.

I think I can use Seperate Logger Class ( For using collect Logger , using nest application booting logger )

Thank you for reply ! 👍👍

**Comment by jiho-kr** [comment]
I`m  wary of libraries becoming bloated.

what is the problem you have?
