### ISSUE TITLE
[Discussion] how about removing default value of `outputDirectory` option for the config scanner

### ISSUE THREAD

**Issue by thilllon** [woowabros/nestjs-library-config#46]
hi,
The config scanner creates or updates the readme file at the project root automatically, and it is a little annoying in some cases. I found that there is an option for setting the output path of artifacts but I couldn't find an option to turn it off. There is a default value for the option. It might be great if the user can control that.

I have 2 suggestions.
1. By removing the default value for `configScannerOptions.outputDirectory`, `outputDirectory`'s type is `string | undefined`. But this way makes breaking changes because the projects which don't use this option should pass the explicit output path for the option.
2. loosening the type for it; allowing `null`
```ts
outputDirectory: '/some/path/to/save' // use the explicit value
outputDirectory: undefined // use default value e.g., "README.md"
outputDirectory: null // do not make or modify md or json file
```
But the caveat is... it is not the semantic way.

any idea?

**Comment by jiho-kr** [comment]
I think it's better to have the outputDirectory specified rather than `ambiguous` due to undefined or null.

And removing the default causes a `breaking change`.

**Comment by thilllon** [comment]
There is no option to stop creating or modifying `.md` or `.json` file currently. Is there any reason not to do so? @jiho-kr

**Comment by jiho-kr** [comment]
I think the `goal` of the config scanner is to `create file` (.md or .json).
That's why i think the outputDirectory always exists.

How do you think it should behave when outputDirectory is null or undefined?

**Comment by thilllon** [comment]
>I think the goal of the config scanner is to create file (.md or .json).
>That's why i think the outputDirectory always exists.

I totally agree! Creating or modifying the file (which includes env or config information) is the purpose of `config-scanner` itself, not of THIS library, as long as I understand correctly. Please tell me if I am wrong.

>What do you think it should behave when outputDirectory is null or undefined?
As I mentioned earlier, I know that adding `null` type is not semantic. But there is no choice but to deactivate the auto-generation of the file without `breaking changes`, as you said. That is exactly why I made this thread to discuss.
I suggested, 2 methods.
The first one makes `breaking change` but more semantic way:
- `outputDirectory` option value should be passed explicitly.
The second one makes no `breaking change` but no lost semantics: null
- `outputDirectory` option value can have `null` type and if it has null, then config scanner does not do anything.
 
thanks for your reply

**Comment by jiho-kr** [comment]
The goal of config-scanner is to `create a file`,  I don't understand why you would want to `deactivate the creation of a file`.

If you don't want to create a file, don't call config-scanner.

**Comment by thilllon** [comment]
My bad. I thought that I couldn't control calling it. Thanks
